spring:
  application:
    name: module03-entity-mapping
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: wanted
    password: wanted
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      # create : 실행 시 테이블 drop 후 새로 생성한다. 기존 데이터 삭제
      # create : 시작 시 테이블 생성, 종료 시 삭제
      # update : 변경 된 엔티티만 반영 -> 개발환경에서 사용
      # none : 아무 작업도 하지 않는다. -> ERD 읽혀둔 것으로 진행할 때 (DB 스키마 직접 관리)
    properties:
      hibernate:
        format_sql: true

